[workspace]
members = ["crab-data-event","libs/crab-common-utils", "libs/crab-types",
    # -- Libraries
    # -- Binaries
    "crab-data-event",
]
default-members = [
    # -- Libraries
    "libs/crab-common-utils", "libs/crab-types",
    # -- Binaries
    "crab-data-event",
]

resolver = "2"

[workspace.dependencies]
# CrabTapestry Ecosystem
crab-common-utils = { path = "libs/crab-common-utils", version = "0.1.0" }
crab-types = { path = "libs/crab-types", version = "0.1.0" }


# Async
tokio = { version = "1.44.2", default-features = false, features = ["macros", "net", "rt-multi-thread", "signal", "time"] }
futures-util = "0.3.31"
crossbeam = "0.8.4"
futures = "0.3.31"

# barter-data
barter-data = { git = "https://github.com/ztNozdormu/barter-rs.git", branch = "dev-local", package = "barter-data" }

# tracing
ms-tracing ={ git = "https://github.com/mountainsea-lab/ms-tracing.git", branch = "main", version = "0.1.6"}

# SerDe
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

# Misc
chrono = { version = "0.4.39", features = ["serde"] }

# Time
time = { version = "0.3.41" ,features = ["serde"]}