[workspace]
members = ["libs/crab-common-utils", "libs/crab-types",
    # -- Libraries
    # -- Binaries
]
default-members = [
    # -- Libraries
    "libs/crab-common-utils", "libs/crab-types",
    # -- Binaries
]

resolver = "2"

[workspace.dependencies]
# Mountquant Ecosystem
crab-common-utils = { path = "libs/crab-common-utils", version = "0.1.0" }
crab-types = { path = "libs/crab-types", version = "0.1.0" }

