version: "3.9"

x-defaults: &defaults
  env_file:
    - .env
  environment:
    # 默认连接本地 Redis
    REDIS_URL: ${REDIS_URL:-redis://redis:6379}

services:
  # ===============================
  # crab-data-event / crab-data-event 服务
  # ===============================
  crab-data-event:
    <<: *defaults
    build:
      context: ./crab-data-event
      dockerfile: Dockerfile
      args:
        # 是否使用本地 Redis，默认为 true
        USE_LOCAL_REDIS: ${USE_LOCAL_REDIS:-true}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .env:/app/.env
    ports:
      - "8080:8080"  # 如果 crab-data-event 提供 HTTP 服务

  # ===============================
  # 可选本地 Redis 服务
  # ===============================
  redis:
    build:
      context: ./vendor/redis
      dockerfile: Dockerfile
    container_name: local-redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: redis-server /usr/local/etc/redis/redis.conf --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - local-redis  # 本地 Redis 可通过 profile 控制是否启动

volumes:
  redis-data:
