version: "3.9"

services:
  crab-data-event:
    build:
      context: .
      dockerfile: ./crab-data-event/Dockerfile
      args:
        SERVICE_NAME: crab-data-event
    env_file:
      - ${CRAB_DATA_EVENT_ENV}
    volumes:
      - ${CRAB_DATA_EVENT_ENV}:/app/.env
      - ./deploy/start-app.sh:/deploy/start-app.sh
    command: ["crab-data-event"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - WAIT_FOR_REDIS=yes
    ports:
      - 10086:10086

  crab-hmds:
    build:
      context: .
      dockerfile: ./crab-hmds/Dockerfile
      args:
        SERVICE_NAME: crab-hmds
    env_file:
      - ${CRAB_HMDS_ENV}
    volumes:
      - ${CRAB_HMDS_ENV}:/app/.env
      - ./deploy/start-app.sh:/deploy/start-app.sh
    command: ["crab-hmds"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WAIT_FOR_MYSQL=yes
    ports:
      - 10088:10088
