services:
  indexer:
    image: crab-data-event
    build:
      context: ./crab-data-event
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy


  redis:
    build:
      context: ./vendor/redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1.5G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: redis-server /usr/local/etc/redis/redis.conf --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  redis-data: