# 每行最大宽度（常见 100 / 120）
max_width = 120

# 使用空格缩进
hard_tabs = false
tab_spaces = 4

# 当前 Rust edition
edition = "2024"

# 自动重新排序 imports（稳定可用）
reorder_imports = true

# 链式调用格式控制：在超出宽度时自动换行
chain_width = 80

# 控制 struct/enum 初始化时的宽度
struct_lit_width = 40
