version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: crab-mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crabtapestry
      MYSQL_USER: crab
      MYSQL_PASSWORD: 123456
    volumes:
      - /usr/local/mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: crab-redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
