[package]
name = "crab-hmds"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async
async-trait = {workspace = true}
# CrabTapestry Ecosystem
crab-common-utils = { workspace = true }
crab-infras = { workspace = true }