[package]
name = "crab-hmds"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async
tokio = {workspace = true, features = ["full"]}
async-trait = {workspace = true}
futures-util = { workspace = true }
crossbeam = { workspace = true }
async-stream = "0.3.6"

# barter-data
barter-data = { workspace = true }

# tracing
ms-tracing = { workspace = true }

# CrabTapestry Ecosystem
crab-common-utils = { workspace = true }
crab-infras = { workspace = true }
crab-types  = {workspace = true}
trade_aggregation = { workspace = true }

# Error
anyhow = {workspace = true}

# Time
chrono = {workspace = true}

# SerDe Data
dashmap =  { workspace = true }
serde_json = { workspace = true }
futures = "0.3.31"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"

# Db
diesel = {workspace = true}

[dev-dependencies]
criterion = { version = "0.7.0", features = ["async"] }

[[bench]]
name = "data_buffer_bench"
harness = false
