[package]
name = "crab-hmds"
version = "0.1.0"
edition = "2024"

[dependencies]
# Async
tokio = {workspace = true}
async-trait = {workspace = true}
futures-util = { workspace = true }
crossbeam = { workspace = true }
async-stream = "0.3.6"
# tracing
ms-tracing = { workspace = true }

# CrabTapestry Ecosystem
crab-common-utils = { workspace = true }
crab-infras = { workspace = true }
crab-types  = {workspace = true}

# Error
anyhow = {workspace = true}

# Time
chrono = {workspace = true}

# SerDe Data
dashmap =  { workspace = true }
#crossbeam-queue = "0.3.12"

