[[subscriptions]]
exchange = "BinanceFuturesUsd"
default_periods = ["1m", "5m", "1h"]
symbols = [
    { name = "btc", quote="usdt", periods = ["1m", "5m", "1h"] },
    { name = "eth", quote="usdt", periods = ["1m"] }
]

#[[subscriptions]]
#exchange = "okx"
#default_periods = ["1m", "5m", "1h"]
#symbols = [
#    { name = "BTC/USDT", periods = ["15m"] }
#]
