[package]
name = "crab-data-event"
version = "0.1.0"
edition = "2024"

[dependencies]
# CrabTapestry Ecosystem
crab-types = { workspace = true }

# Async
tokio = { workspace = true }
futures-util = { workspace = true }
crossbeam = { workspace = true }
futures = { workspace = true }

# barter-data
barter-data = { workspace = true }

# tracing
ms-tracing = { workspace = true }

# SerDe
serde = { workspace = true }

# Time
time = { version = "0.3.41" ,features = ["serde"]}

# Cryto
trade_aggregation = "13.0.1"