[package]
name = "crab-insight"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
axum-extra = { version = "0.10.3", features = ["cookie"]}

tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors","trace"] }

tokio.workspace = true
async-trait = { workspace = true }

argon2 = "0.5.3"
chrono.workspace = true
dotenv = "0.15.0"
jsonwebtoken =  { version = "10", features = ["aws_lc_rs"] }
lettre = "0.11.19"
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.8.6", features = ["runtime-async-std-native-tls", "mysql", "chrono", "uuid"] }
time.workspace = true
validator = { version = "0.20.0", features = ["derive"] }
ms-tracing.workspace = true
