name: Build & Push Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - crab-data-event
          - crab-hmds
          # - future-service  # 未来可扩展

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug workspace files
        run: |
          echo "=== 当前路径 ==="
          pwd
          echo "=== 根目录文件 ==="
          ls -lah
          echo "=== crab-data-event 目录 ==="
          ls -lah crab-data-event || true
          echo "=== crab-hmds 目录 ==="
          ls -lah crab-hmds || true
          echo "=== libs 目录 ==="
          ls -lah libs || true

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          build-args: |
            SERVICE_NAME=${{ matrix.service }}
          tags: |
            mountainsealab/${{ matrix.service }}:${{ github.ref_name }}
            mountainsealab/${{ matrix.service }}:latest
